### ISSUE TITLE
Sandwichable crash

### ISSUE THREAD

**Issue by Infant-Anihilator** [milkev/Meal-API-Addon#1]
the game didn't generate a crash log, but the crash only happens when i install this mod.

i made a sandwich using 2 bread slices, 2 apple slices, and 2 nectarines from the croptopia mod.
idk man thats about it

**Comment by milkev** [comment]
ill take a look at this in the morning, im not really sure why it would crash though 🤔

**Comment by Infant-Anihilator** [comment]
it could have something to do with mixing croptopia and sandwichable. i'm not a mod creator at all, this is just an educated guess

**Comment by milkev** [comment]
i dont think it had anything to do with croptopia. i took a look at the logs it generates and it just happens when you eat any sandwich.
this mods logic doubles up sandwiches logic though, so just not applying my logic to sandwiches should work. should be an easy fix, ill be able to push it tomorrow.

**Comment by milkev** [comment]
Fixed with 1.0.1
Thanks for reporting this!

**Comment by Infant-Anihilator** [comment]
awesome
